name: solitaire
description: A simple solitaire app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+0

environment:
  sdk: '>=3.0.0 <3.10.6'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  settings_ui: ^2.0.2
  path_provider: ^2.0.15
  package_info_plus: ^4.1.0
  logging: ^1.2.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/back_side.png
    - assets/gear.png
    - assets/cards/
    - assets/cards/backs/
